### ISSUE TITLE
Описание каждой строчки:

### ISSUE THREAD

**Issue by Rosya-edwica** [MaryLazareva/fastapi_microservices#1]
https://github.com/MaryLazareva/fastapi_microservices/blob/1d4397175b1a1c05e3b11b32a5c68c08bbffcf3d/docker-compose-kafka.yaml#L1C1-L18C18

```yaml
version: '2' # Версия синтаксиса docker-compose файла

services: # Здесь определяются все сервисы (контейнеры), которые будут запущены

  zookeeper: # Имя первого сервиса
    image: confluentinc/cp-zookeeper:latest # Образ Docker, который будет использован для этого сервиса
    environment: # Переменные окружения, которые будут установлены в контейнере
      ZOOKEEPER_CLIENT_PORT: 2181 # Порт, на котором слушает клиент Zookeeper

  kafka: # Имя второго сервиса
    image: confluentinc/cp-kafka:latest # Образ Docker, который будет использован для этого сервиса
    depends_on: # Список сервисов, от которых зависит этот сервис. Docker-compose будет стараться запустить их перед этим сервисом
      - zookeeper # Этот сервис зависит от сервиса zookeeper
    environment: # Переменные окружения, которые будут установлены в контейнере
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181 # Адрес и порт, на котором Kafka может подключиться к Zookeeper
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://kafka:9092 # Список прослушивателей, которые Kafka будет анонсировать для клиентов
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1 # Фактор репликации для темы смещений в Kafka
    ports: # Сопоставление портов между хостом и контейнером
      - 9092:9092 # Порт 9092 на хосте будет сопоставлен с портом 9092 в контейнере
```
